<?php
/**
 * @file
 * Code for the SnazziSweets Base feature.
 */

include_once 'snazzisweets_base.features.inc';

/**
 * Implements hook_block_info().
 */
function snazzisweets_base_block_info() {
  $blocks = array();
  $blocks['snazzi_contact'] = array(
    'info' => t('Snazzi Contact Information'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function snazzisweets_base_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'snazzi_contact' :
		$block['subject'] = t('Contact Information'); 
		$block['content'] = 
		'<div class="snazzi-contactus-block hidden-xs">
			<div class="snazzi-email-title">Email</div>
			<div class="snazzi-email-contents"><a class="href="mailto:orders@snazzisweets.ca">orders@snazzisweets</a></div>
			<div class="snazzi-phone-title">Phone</div>
			<div class="snazzi-phone-contents"><a href="tel:6138988545">613-898-8545</a></div>
			<div class="snazzi-location-contents">Serving the Ottawa area, from Orleans to Kanata</div>
		</div>
		<button class="visible-xs btn btn-default btn-xs" data-toggle="collapse" data-target="#email-menu">Email</button>
		<div id="email-menu" class="collapse">
			<a href="mailto:orders@snazzisweets.ca">orders@snazzisweets</a>
		</div>
		<button class="visible-xs btn btn-default btn-xs" data-toggle="collapse" data-target="#phone-menu">Phone/SMS</button>
		<div id="phone-menu" class="collapse">
			<a href="tel:6138988545">613-898-8545</a>
		</div>
		<button class="visible-xs btn btn-default btn-xs" data-toggle="collapse" data-target="#location-menu">Service Area</button>
		<div id="location-menu" class="collapse">
			Serving the Ottawa area, from Orleans to Kanata
		</div>'; 
	




		break;
  }
  
  return $block;
}

function snazzisweets_base_preprocess_page(&$vars) {
	$snazzi_cart = menu_navigation_links('menu-snazzi-navbar');
	$vars['snazzi_cart'] = theme('links__menu_snazzi_navbar', array(
			'links' => $snazzi_cart,
			'attributes' => array(
				'id' => 'snazzi-cart',
				'class' => array('links', 'clearfix', 'snazzi-cart', 'nav', 'navbar-nav'),
			),
		)
	);
}

/**
 * Implements hook_entity_info_alter().
 */
function snazzisweets_base_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['snazzi_ubercart_cart_view'] = array(
    'label' => t('Snazzi Ubercart View'),
    'custom settings' => TRUE,
  );
}

function snazzisweets_base_preprocess_node(&$vars) {
  if (($vars['node']->type == 'snazzi_cookie' || $vars['node']->type == 'snazzi_cupcake') 
      && $vars['view_mode'] == 'snazzi_ubercart_cart_view') {
    $vars['theme_hook_suggestions'][] = 'node__snazzi_ubercart_cart_view';
  }
}

function snazzisweets_base_form_uc_cart_checkout_form_alter(&$form, &$form_state) {
  unset($form['panes']['billing']['select_address']);
}

/*function snazzisweets_base_preprocess_node(&$variables) {
  
  if ($variables['type'] == 'snazzi_cookie' && $variables['view_mode'] == 'snazzi_ubercart_cart_view'){
    //React to the Cookie Jar
    
    //If the title is visible, hide it
//    if(isset($variables['title'])){
  //    $variables['title'] = FALSE;
    //}
  }      
  else if ($variables['type'] == 'snazzi_cake' && $variables['view_mode'] == 'teaser'){
    //React to the Cake Carousel
    
    //If the title is visible, hide it
    if(isset($variables['title'])){
      $variables['title'] = FALSE;
    }
  }
  else if ($variables['type'] == 'snazzi_cupcake' && $variables['view_mode'] == 'teaser'){
    //React to the Cupcake Carousel
    
    //Set the linked path to the page URL, with nid appended
    $variables['content']['field_snazzi_photo'][0]['#path']['path'] = 'cupcakes/'.$variables['nid'];
    
    //If the title is visible, hide it
    if(isset($variables['title'])){
      $variables['title'] = FALSE;
    }
  }
}*/


/*function snazzisweets_base_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#bundle'] == 'snazzi_cookie' &&
    $variables['element']['#view_mode'] == 'snazzi_ubercart_cart_view'){
    //React to Cookie Cart Contents
    if ($variables['element']['#field_name'] == 'body'){
      $variables['classes_array'][] = 'col-xs-6';
    } 
    else if ($variables['element']['#field_name'] == 'uc_product_image'){
      $variables['classes_array'][] = 'col-xs-3';
    }
  }
  
}*/
/*function snazzisweets_base_form_alter(&$form, &$form_state, $form_id){
	if (strpos($form_id, "uc_product_add_to_cart_form") === 0) {
		$qty_per_package = array(0 => t('6 per package'), 1 => t('12 per package'));
		
		$form['qty_pre_package'] = array(
			'#type' => 'radios',
			'#title' => 'Quantity per Package',
			'#default_value' => 0,
			'#options' => $qty_per_package,
			'#description' => t('Number of treats in each bag or box.'),
			'#weight' => 0
		);
		$form['qty']['#weight'] = 5;
		$form['actions']['#weight'] = 10;
		kpr($form);
	}
}



//HELPER FUNCTIONS
function startsWith($haystack, $needle)
{
	$length = strlen($needle);
	return (substr($haystack, 0, $length) === $needle);
}

function endsWith($haystack, $needle)
{
	$length = strlen($needle);
	if ($length == 0) {
		return true;
	}
	return (substr($haystack, -$length) === $needle);
}*/