<?php
/**
 * @file
 * Code for the SnazziSweets Base feature.
 */

include_once 'snazzisweets_base.features.inc';

/**
 * Implements hook_block_info().
 */
function snazzisweets_base_block_info() {
  $blocks = array();
  $blocks['snazzi_contact'] = array(
    'info' => t('Snazzi Contact Information'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function snazzisweets_base_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'snazzi_contact' :
		$block['subject'] = t('Email'); 
		$block['content'] = '<div class="snazzi-email-link"><a href="mailto:orders@snazzisweets.ca">orders@snazzisweets</a></div>'; 
		break;
  }
  
  return $block;
}

function snazzisweets_base_preprocess_page(&$vars) {
	$snazzi_cart = menu_navigation_links('menu-snazzi-navbar');
	$vars['snazzi_cart'] = theme('links__menu_snazzi_navbar', array(
			'links' => $snazzi_cart,
			'attributes' => array(
				'id' => 'snazzi-cart',
				'class' => array('links', 'clearfix', 'snazzi-cart', 'nav', 'navbar-nav'),
			),
		)
	);
}


function snazzisweets_base_preprocess_node(&$variables) {
  
  if ($variables['type'] == 'snazzi_cookie' && $variables['view_mode'] == 'snazzi_ubercart_cart_view'){
    //React to the Cookie Jar
    
    //If the title is visible, hide it
//    if(isset($variables['title'])){
  //    $variables['title'] = FALSE;
    //}
  }      
  else if ($variables['type'] == 'snazzi_cake' && $variables['view_mode'] == 'teaser'){
    //React to the Cake Carousel
    
    //If the title is visible, hide it
    if(isset($variables['title'])){
      $variables['title'] = FALSE;
    }
  }
  else if ($variables['type'] == 'snazzi_cupcake' && $variables['view_mode'] == 'teaser'){
    //React to the Cupcake Carousel
    
    //Set the linked path to the page URL, with nid appended
    $variables['content']['field_snazzi_photo'][0]['#path']['path'] = 'cupcakes/'.$variables['nid'];
    
    //If the title is visible, hide it
    if(isset($variables['title'])){
      $variables['title'] = FALSE;
    }
  }
}


function snazzisweets_base_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#bundle'] == 'snazzi_cookie' &&
    $variables['element']['#view_mode'] == 'snazzi_ubercart_cart_view'){
    //React to Cookie Cart Contents
    if ($variables['element']['#field_name'] == 'body'){
      $variables['classes_array'][] = 'col-xs-6';
    } 
    else if ($variables['element']['#field_name'] == 'uc_product_image'){
      $variables['classes_array'][] = 'col-xs-3';
    }
  }
  
}
/*function snazzisweets_base_form_alter(&$form, &$form_state, $form_id){
	if (strpos($form_id, "uc_product_add_to_cart_form") === 0) {
		$qty_per_package = array(0 => t('6 per package'), 1 => t('12 per package'));
		
		$form['qty_pre_package'] = array(
			'#type' => 'radios',
			'#title' => 'Quantity per Package',
			'#default_value' => 0,
			'#options' => $qty_per_package,
			'#description' => t('Number of treats in each bag or box.'),
			'#weight' => 0
		);
		$form['qty']['#weight'] = 5;
		$form['actions']['#weight'] = 10;
		kpr($form);
	}
}



//HELPER FUNCTIONS
function startsWith($haystack, $needle)
{
	$length = strlen($needle);
	return (substr($haystack, 0, $length) === $needle);
}

function endsWith($haystack, $needle)
{
	$length = strlen($needle);
	if ($length == 0) {
		return true;
	}
	return (substr($haystack, -$length) === $needle);
}*/